/* Generated By:JavaCC: Do not edit this line. KoreParserConstants.java */
package org.kframework.parser.kore;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KoreParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int TOKLABEL = 23;
  /** RegularExpression Id. */
  int REWRITE = 24;
  /** RegularExpression Id. */
  int EQUAL = 25;
  /** RegularExpression Id. */
  int LCELLPR = 26;
  /** RegularExpression Id. */
  int RCELLPR = 27;
  /** RegularExpression Id. */
  int LENDPR = 28;
  /** RegularExpression Id. */
  int RCELLPRDOT = 29;
  /** RegularExpression Id. */
  int LENDPRDOT = 30;
  /** RegularExpression Id. */
  int LPR = 31;
  /** RegularExpression Id. */
  int RPR = 32;
  /** RegularExpression Id. */
  int LCURLY = 33;
  /** RegularExpression Id. */
  int RCURLY = 34;
  /** RegularExpression Id. */
  int LSQUARE = 35;
  /** RegularExpression Id. */
  int RSQUARE = 36;
  /** RegularExpression Id. */
  int SORT_ID = 37;
  /** RegularExpression Id. */
  int LABELCONSTANT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUM>",
    "<DIGIT>",
    "<STRING>",
    "\"true\"",
    "\"false\"",
    "\"# \"",
    "\":\"",
    "\"::\"",
    "\".K\"",
    "\",\"",
    "\"~>\"",
    "\".KList\"",
    "\".Bag\"",
    "\"color\"",
    "\"multiplicity\"",
    "\"stream\"",
    "\"requires\"",
    "\"ensures\"",
    "\"2KLabel\"",
    "\"=>\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "\">...\"",
    "\"...</\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<SORT_ID>",
    "<LABELCONSTANT>",
  };

}
