/* Generated By:JavaCC: Do not edit this line. KoreParser.java */
package org.kframework.parser.kore;

import org.kframework.kil.Term;
import org.kframework.kil.ASTNode;
import org.kframework.kil.IntBuiltin;
import org.kframework.kil.BoolBuiltin;
import org.kframework.kil.StringBuiltin;
import org.kframework.kil.KLabelConstant;
import org.kframework.kil.KLabel;
import org.kframework.kil.KList;
import org.kframework.kil.KSequence;
import org.kframework.kil.KApp;
import org.kframework.kil.KInjectedLabel;
import org.kframework.kil.Variable;
import org.kframework.kil.Bag;
import org.kframework.kil.Rewrite;
import org.kframework.kil.Cell;
import org.kframework.kil.Sentence;
import java.util.ArrayList;
import java.util.HashMap;
import org.kframework.kil.loader.Context;
import java.io.StringReader;

import org.kframework.utils.errorsystem.KException.ExceptionType;
import org.kframework.utils.errorsystem.KException.KExceptionGroup;
import org.kframework.utils.errorsystem.KException;
import org.kframework.utils.general.GlobalSettings;


public class KoreParser implements KoreParserConstants {
  private String filename;

  /** Parses a given string that was read from 'stringSentence'. */
  public static Sentence parse(String filename, String string, Context context) {
    KoreParser parser = new KoreParser(new StringReader(string));
    try {
      return parser.parseTopLevel(context);
    } catch (ParseException e) {
      // TODO: report location
      GlobalSettings.kem.register(new KException(
        ExceptionType.ERROR, KExceptionGroup.PARSER, e.toString(), filename, null));
      return null;
    } catch (TokenMgrError e) {
      GlobalSettings.kem.register(new KException(
        ExceptionType.ERROR, KExceptionGroup.PARSER, e.toString(), filename, null));
      return null;
    }
  }

  static final public Sentence parseTopLevel(Context context) throws ParseException {
                                           Term col;Term req;Term ens;
    col = parseCollection(context);
    jj_consume_token(20);
    req = parseKApp(context);
    jj_consume_token(21);
    ens = parseKApp(context);
 Sentence result = new Sentence(); result.setBody(col);
        result.setRequires(req);result.setEnsures(ens); {if (true) return result;}
    throw new Error("Missing return statement in function");
  }

  static final public Term parseCollection(Context context) throws ParseException {
                                         ArrayList<Term> temp = new ArrayList<Term>();Term a;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUM:
    case STRING:
    case 8:
    case 9:
    case 10:
    case 12:
    case 15:
    case SORT_ID:
    case SORTKINJECT:
    case LABELCONSTANT:
      a = parseKList(context);
 {if (true) return a;}
      break;
    case 16:
    case LCELLPR:
    case LPR:
      label_1:
      while (true) {
        a = parseCell(context);
                         temp.add(a);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 16:
        case LCELLPR:
        case LPR:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
      }
 {if (true) return new Bag(temp);}
      break;
    default:
      jj_la1[1] = jj_gen;

    }
    throw new Error("Missing return statement in function");
  }

  static final public Term parseCell(Context context) throws ParseException {
                                   Token label;Token endLabel;Term cellContents;
                boolean leftEclipse;boolean rightEclipse;Term left;Term right;HashMap<String,String> attributes;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 16:
      jj_consume_token(16);
  {if (true) return (Term)(Bag.EMPTY);}
      break;
    case LCELLPR:
      jj_consume_token(LCELLPR);
      label = jj_consume_token(PUREVAR);
      attributes = parseAttributes();
      leftEclipse = parseLeftEclipse();
      cellContents = parseCollection(context);
      rightEclipse = parseRightEclipse();
      endLabel = jj_consume_token(PUREVAR);
      jj_consume_token(RCELLPR);
 if(label.equals(endLabel))
        if(leftEclipse)
        { if (rightEclipse)
                {if (true) return new Cell(label.image,cellContents,attributes,"both");}
          else
                {if (true) return new Cell(label.image,cellContents,attributes,"left");}
        } else if (rightEclipse)
                {if (true) return new Cell(label.image,cellContents,attributes,"right");}
          else
                {if (true) return new Cell(label.image,cellContents,attributes,"none");}
      break;
    case LPR:
      jj_consume_token(LPR);
      left = parseCollection(context);
      jj_consume_token(REWRITE);
      right = parseCollection(context);
      jj_consume_token(RPR);
 {if (true) return  new Rewrite(left, right, context);}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public boolean parseLeftEclipse() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RCELLPR:
      jj_consume_token(RCELLPR);
 {if (true) return false;}
      break;
    case RCELLPRDOT:
      jj_consume_token(RCELLPRDOT);
 {if (true) return true;}
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public boolean parseRightEclipse() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LENDPR:
      jj_consume_token(LENDPR);
 {if (true) return false;}
      break;
    case LENDPRDOT:
      jj_consume_token(LENDPRDOT);
 {if (true) return true;}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public HashMap<String,String> parseAttributes() throws ParseException {
         HashMap<String,String > temp = new HashMap<String,String >();Token a;Token b;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 17:
      case 18:
      case 19:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 17:
        a = jj_consume_token(17);
        jj_consume_token(EQUAL);
        b = jj_consume_token(STRING);
        break;
      case 18:
        a = jj_consume_token(18);
        jj_consume_token(EQUAL);
        b = jj_consume_token(STRING);
        break;
      case 19:
        a = jj_consume_token(19);
        jj_consume_token(EQUAL);
        b = jj_consume_token(STRING);
          if(a.image.equals("color"))
                temp.put("color",b.image);
          else if(a.image.equals("multiplicity"))
                temp.put("multiplicity",b.image);
                else if(a.image.equals("stream"))
                temp.put("stream",b.image);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
               {if (true) return temp;}
    throw new Error("Missing return statement in function");
  }

  static final public Term parseKList(Context context) throws ParseException {
                                    ArrayList<Term> temp = new ArrayList<Term>();Term a;Term e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 15:
      jj_consume_token(15);
 {if (true) return KList.EMPTY;}
      break;
    case NUM:
    case STRING:
    case 8:
    case 9:
    case 10:
    case 12:
    case SORT_ID:
    case SORTKINJECT:
    case LABELCONSTANT:
      a = parseKSeq(context);
 temp.add(a);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 13:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_3;
        }
        jj_consume_token(13);
        e = parseKSeq(context);
 temp.add(e);
      }
 {if (true) return new KList(temp);}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Term parseKSeq(Context context) throws ParseException {
                                  ArrayList<Term> temp = new ArrayList<Term>();Term a;Term e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 12:
      jj_consume_token(12);
        {if (true) return KSequence.EMPTY;}
      break;
    case NUM:
    case STRING:
    case 8:
    case 9:
    case 10:
    case SORT_ID:
    case SORTKINJECT:
    case LABELCONSTANT:
      a = parseKApp(context);
 temp.add(a);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 14:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_4;
        }
        jj_consume_token(14);
        e = parseKApp(context);
 temp.add(e);
      }
 {if (true) return new KSequence(temp);}
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Term parseKApp(Context context) throws ParseException {
                                 Term a; Term b; Term c=null;
    a = parseLabel(context);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPR:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
      jj_consume_token(LPR);
      b = parseKList(context);
      jj_consume_token(RPR);
                                                                c=new KApp(a,b);a=c;
    }
   {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  static final public Term parseLabel(Context context) throws ParseException {
 Token n;Term a;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 10:
    case SORTKINJECT:
      if (jj_2_1(2)) {
        a = choiceInjectOne(context);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 10:
          a = choiceInjectTwo(context);
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
 {if (true) return a;}
      break;
    case NUM:
      n = jj_consume_token(NUM);
               {if (true) return (KLabel)IntBuiltin.of(Integer.parseInt(n.image));}
      break;
    case STRING:
      n = jj_consume_token(STRING);
                  {if (true) return (KLabel)StringBuiltin.of(n.image);}
      break;
    case 8:
      jj_consume_token(8);
          {if (true) return (KLabel)BoolBuiltin.of("true");}
      break;
    case 9:
      jj_consume_token(9);
           {if (true) return (KLabel)BoolBuiltin.of("false");}
      break;
    case LABELCONSTANT:
      n = jj_consume_token(LABELCONSTANT);
                        {if (true) return (KLabel) KLabelConstant.of(n.image);}
      break;
    case SORT_ID:
      if (jj_2_2(2)) {
        a = choiceOne();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SORT_ID:
          a = choiceTwo();
          break;
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
 {if (true) return a;}
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Term choiceInjectOne(Context context) throws ParseException {
                                          Term e;
    jj_consume_token(SORTKINJECT);
    jj_consume_token(LPR);
    e = parseCollection(context);
    jj_consume_token(RPR);
                                                              {if (true) return (Term)(new KInjectedLabel(e));}
    throw new Error("Missing return statement in function");
  }

  static final public Term choiceInjectTwo(Context context) throws ParseException {
                                         Term e;
    jj_consume_token(10);
    jj_consume_token(LPR);
    e = parseCollection(context);
    jj_consume_token(RPR);
 {if (true) return (Term)(new KInjectedLabel(e));}
    throw new Error("Missing return statement in function");
  }

  static final public Term choiceOne() throws ParseException {
                     Token n;Token m;
    n = jj_consume_token(SORT_ID);
    jj_consume_token(11);
    m = jj_consume_token(SORT_ID);
                                       {if (true) return (Term)(new Variable(n.image,m.image));}
    throw new Error("Missing return statement in function");
  }

  static final public Term choiceTwo() throws ParseException {
                    Token n;
    n = jj_consume_token(SORT_ID);
 {if (true) return (Term)KLabelConstant.of(n.image);}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_3R_6() {
    if (jj_scan_token(SORTKINJECT)) return true;
    if (jj_scan_token(LPR)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_6()) return true;
    return false;
  }

  static private boolean jj_3R_7() {
    if (jj_scan_token(SORT_ID)) return true;
    if (jj_scan_token(11)) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_7()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public KoreParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[15];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x21010000,0x210197a0,0x21010000,0xa000000,0x14000000,0xe0000,0xe0000,0x2000,0x97a0,0x4000,0x17a0,0x20000000,0x400,0x0,0x7a0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x7,0x0,0x0,0x0,0x0,0x0,0x0,0x7,0x0,0x7,0x0,0x0,0x1,0x7,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[2];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public KoreParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public KoreParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new KoreParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public KoreParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new KoreParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public KoreParser(KoreParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(KoreParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[35];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 15; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 35; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
